export default [
    "A political history of",
    "A social history of ",
    "An economic history of ",
    "A cultural history of ",
    "A family history of",
    "A labour history of",
    "An intellectual history of",
    "A religious history of",
    "A legal history of",
    "A public history of",
    "An imperial history of",
    "A military history of ",
    "An educational history of",
    "An oral history of",
    "A linguistic history of ",
    "An ethnographic history of",
    "An ecological history of ",
    "A business history of ",
    "An environmental history of",
    "An institutional history of",
    "A comparative history of ",
    "A medical history of",
    "A food history of ",
    "A queer history of",
    "An art history of ",
    "An aesthetic history of ",
    "A biographic history of ",
];