export default [
    "in Canada",
    "in New Zealand",
    "in Britain",
    "in India",
    "in the Caribbean",
    "in space",
    "on the Moon",
    "in Russia",
    "in Alaska",
    "across continents",
    "in the oceans",
    "in Kingston, Ontario",
    "in Peru",
    "in the Azores",
    "in the Bahamas",
    "in London, Ontario",
    "in the British World",
    "on the 49th Parallel",
    "in the Alps",
    "on Mount Everest",
    "in Japan",
    "on islands",
    "in Antarctica",
    "in Asia",
    "in Europe",
    "in North America",
    "in Africa",
    "in South America",
    "in the Champagne region of France",
    "in the World",
    "in Pangaea",
    "in Cascadia",
    "in Middle Earth",
    "in China",
    "in North Korea",
    "in the Falkland Islands",
    "in Newfoundland & Labrador",
    "in Suriname",
    "in Sardinia",
    "in the Appalachians",
    "in the Deep South",
    "in Scandinavia",
    "on the International Space Station",
    "in Area 51",
];