export default [
    "using Foucauldian theory.",
    "using a global approach.",
    "using a transnational approach.",
    "using Gramscian theory.",
    "using the Liberal Order Framework.",
    "using a local perspective.",
    "using methodological nationalism.",
    "using Habermasian theory.",
    "using an intersectional lens.",
    "using Marxist theory.",
    "using material culture theory.",
    "using postcolonial theory.",
    "using discourse theory.",
    "using network analysis.",
    "using an art historical perspective.",
    "using feminist theory.",
    "using a Weberian framework.",
    "using a Borderlands framework. ",
    "using postmodern theory.",
    "using a psychoanalytical approach.",
    "using a utilitarian approach.",
    "using conspiracy theories.",
    "using esoteric theory.",
    "using a phenomenological approach.",
    "through a bifocal lens.",
];