export default [
    "dogs",
    "horticulture",
    "taxes",
    "constitutions",
    "homes",
    "science",
    "space",
    "prostitution",
    "Scientology",
    "children",
    "maps",
    "immigration",
    "books",
    "popular culture",
    "state-building",
    "credit",
    "Botchy",
    "policing",
    "railways",
    "teapots",
    "coffee",
    "TV Shows",
    "capitalism",
    "international law",
    "pirates",
    "Western esotericism",
    "national parks",
    "logic",
    "beekeeping",
    "Anthropocene",
    "history",
    "failure",
    "memory",
    "suffrage",
    "Schadenfreude",
    "left-handed dictators",
    "dentistry",
    "beer",
    "office politics",
    "radical poetry",
    "sieves and civilisations",
    "procrastination",
    "Big Oil",
    "the Fyre Festival",
    "Tanya Harding",
    "Cleopatra",
    "Dave Coulier",
    "John Rockefeller",
    "hipsters",
    "Aesop",
    "Florence Nightingale",
    "firefighters",
    "haberdashers",
    "innkeepers",
    "Elvis",
    "Charlemagne",
    "stenographers",
    "monks",
    "Jane Austen",
    "Facebook community standards"
];