export default [
    "Medieval",
    "Renaissance",
    "Early Modern",
    "fifteenth-century",
    "sixteenth-century",
    "seventeenth-century",
    "eighteenth-century",
    "nineteenth-century",
    "twentieth-century",
    "Contemporary",
    "Future",
    "long-nineteenth-century",
    "Age of Constitutions",
    "1867",
    "fin de siècle",
    "antebellum",
    "postwar",
    "cold war",
    "postbellum",
    "Interwar",
    "Byzantine",
    "Great Depression",
    "late early modern",
    "Anthropocene",
    "this morning's",
    "days of yore",
    "first contact",
];